<?php
/**
 * @file
 * Code for the Réseau sociaux feature.
 */

include_once 'pnf_social_media.features.inc';

/**
 * Implements hook_init().
 */
function pnf_social_media_init() {
  drupal_add_css(drupal_get_path('module','pnf_social_media') . '/css/pnf_social_media.css');
}

/**
 * Implements hook_block_view_alter().
 */
function pnf_social_media_block_view_alter(&$data, $block)
{
  //dpm($data);
 // dpm($block);
}