<?php
/**
 * @file
 * Drupal needs this blank file.
 */

include_once 'pnf_jobs.features.inc';


/**
 * Implements hook_ds_fields_info().
 */
function pnf_jobs_ds_fields_info($entity_type) {
	$fields = array();

	$fields['node']['btn_job_notice'] = array(
		'title' => t('Job notice button'),
		'field_type' => DS_FIELD_TYPE_FUNCTION,
		'ui_limit' => array('job|*'),
		'function' => 'pnf_jobs_btn_job_notice',
	);

	if (isset($fields[$entity_type])) {
		return array($entity_type => $fields[$entity_type]);
	}
	return;
}

/**
 * Render the field btn_job_notice
 */
function pnf_jobs_btn_job_notice($field) {
	if (!empty($field['entity']->field_job_notice)) {
		$label = t("Job notice - PDF");
		$uri =  $field['entity']->field_job_notice['und'][0]['uri'];
		$url = file_create_url($uri);
		$output = '<a class = "btn btn-sm btn-secondary" href="'. $url .'" target="_blank">'. $label .'</a>';
		return $output;
	}
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function pnf_jobs_pathauto_alias_alter(&$alias, array &$context) {
  if ($context['type'] == 'job') {
	$park_menu = menu_tree('menu-menu-park');
	$single_parent = array_shift($park_menu);
	$single_parent_alias = drupal_get_path_alias($single_parent['#href']);
	$alias = $single_parent_alias . '/' . $alias;
  }
}

/**
 * Implements hook_node_view_alter().
 */
function pnf_jobs_node_view_alter(&$build) {
//  dpm($build);
  if ($build['#bundle'] == 'job' && $build['#view_mode'] == 'full') {
	$job_breadcrumb = pnf_park_breadcrumb();
	drupal_set_breadcrumb($job_breadcrumb);
  }
}

/**
 * Implements hook_views_pre_view().
 */
function pnf_jobs_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'jobs' && $view->current_display != 'page_jobs') {
	drupal_set_breadcrumb(pnf_park_breadcrumb());
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
//function pnf_jobs_form_job_node_form_alter(&$form, &$form_state, $form_id) {
//	if (variable_get('park_code') == 'fcb') {
//		// We must disable the select field field_job_type, set on "Offres d'emploi" value
//		// without removing the other 2 options, otherwise we get a pathauto bug.
//		$form['field_job_type']['#disabled'] = 'disabled';
//	}
//}

/**
 * Implements hook_block_view_alter().
 */
function pnf_jobs_block_view_alter(&$data, $block) {
  if ($block->bid == 'menu-menu-menu-jobs') {
    $park_codes = array('fcb');
    if (in_array(variable_get('park_code'), $park_codes)) {
      $mlids = element_children($data['content']);
      foreach ($mlids as $mlid) {
        if ($data['content'][$mlid]['#href'] == 'civic-services') {
          unset($data['content'][$mlid]);
        }
      }
    }
  }
}
