<?php
/**
 * @file
 * Code for the Mailchimp integration feature.
 */

include_once 'pnf_mailchimp.features.inc';

/**
 * Implements hook_node_view().
 */
function pnf_mailchimp_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'simplenews' && $view_mode == 'full') {
    drupal_add_css(drupal_get_path('module', 'pnf_mailchimp') . '/css/pnf_mailchimp.css');
    drupal_add_css(drupal_get_path('module', 'pnf_newsletter') . '/css/newsletter.css');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pnf_mailchimp_form_mailchimp_campaign_campaign_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_css(drupal_get_path('module', 'pnf_mailchimp') . '/css/pnf_mailchimp.css');

  // If we come from a simplenews page (full mode view)
  // we load the corresponding node to get this title and date
  // to preset Title, Object and Content (the insert entity token) campaign fields.
  if (isset($_GET['snid'])) {
    $sn_wrapper = entity_metadata_wrapper('node', $_GET['snid']);
    $newsletter_title_date = $sn_wrapper->title->value()
      . ' - ' . ucfirst(format_date($sn_wrapper->field_newsletter_date->value(), 'custom', 'F Y'));

    $form['title']['#default_value'] = $newsletter_title_date;
    $form['subject']['#default_value'] = $newsletter_title_date;

    $form['content']['html_wrapper']['html']['#default_value'] =
      '[mailchimp_campaign|entity_type=node|entity_id=' . $_GET['snid'] . '|view_mode=full]';
  }
  // Here, we handle the ajax callback which is fired when selecting a template.
  // Another form field is added to the DOM. We must preset it as well.
  elseif (isset($form['content']['contenu_wrapper']['contenu'])) {
    $snid = explode('=', $_SERVER['HTTP_REFERER'])[1];

    $form['content']['contenu_wrapper']['contenu']['#default_value'] =
      '[mailchimp_campaign|entity_type=node|entity_id=' . $snid . '|view_mode=full]';

    $form['content']['contenu_wrapper']['contenu']['#attributes'] = array('readonly' => 'readonly');
  }

  // In any case, we must properly name the List field, badly translated in French as "Lister".
  $form['list_id']['#title'] = 'Liste';

  // and simplify the Template select field.
  $options = array('-- Sélectionner --');
  $options['Mes gabarits'] =$form['template_id']['#options']['My Custom Templates'];
  $form['template_id']['#options'] = $options;
}
