<?php
/**
 * @file
 * Code for the Rapports scientifiques feature.
 */

include_once 'pnf_scientific_reports.features.inc';

/**
 * Implements hook_node_view().
 */
function pnf_scientific_reports_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'scientific_report') {
    drupal_add_css(drupal_get_path('module', 'pnf_scientific_reports') . '/css/pnf_scientific_reports.css');
    if ($view_mode == 'full') {
      drupal_add_js(drupal_get_path('module', 'pnf_scientific_reports') . '/js/pnf_scientific_reports.js');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pnf_scientific_reports_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-scientific-reports-sr-list') {
    drupal_add_js(drupal_get_path('module', 'pnf_scientific_reports') . '/js/pnf_scientific_reports.js');

  }
}