<?php
/**
 * @file
 * Code for the Documents feature.
 */

include_once 'pnf_documents.features.inc';

/**
 * Implements hook_form_alter().
 */
function pnf_documents_form_alter(&$form, &$form_state, $form_id) {
  // Uuids to be used
  $uuids = array(
    'Communiqué de presse' => '8abe9b99-fc3e-4df1-a402-543ce16b3601',
    'Dossier de presse' => '80b8cbe2-5a72-4d15-807b-3957158dd4cb',
//    'Journal du parc' => '8375bea1-2b5c-411d-9179-1242c90a16aa',
  );

  // If "Documents" exposed filter, we must remove 'Communiqué de presse' and 'Dossier de presse' options.
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-documents-page-documents') {
    $options = $form['field_document_category_tid']['#options'];
    foreach ($options  as $key => $option) {
      if ($key == 'All') continue;
      $term = taxonomy_term_load($key);
      $option_uuid = $term->uuid;
      if (in_array($option_uuid, $uuids)) {
        unset($options[$key]);
      }
    }
    $form['field_document_category_tid']['#options'] = $options;
  }

  // Il "Espace Presse" exposed filter, we must keep only 'All', 'Communiqué de presse' and 'Dossier de presse' options.
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-documents-page-press') {
    $options = $form['field_document_category_tid']['#options'];
    foreach ($options  as $key => $option) {
      if ($key == 'All') continue;
      $term = taxonomy_term_load($key);
      $option_uuid = $term->uuid;
      if (!in_array($option_uuid, $uuids)) {
        unset($options[$key]);
      }
    }
    $form['field_document_category_tid']['#options'] = $options;
  }
}

/**
 * Implementation of hook_menu()
 */
function pnf_documents_menu() {
  $items['download/%file'] = array(
    'page callback' => 'pnf_download_file',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Page callback for forcing a file to download
 */
function pnf_download_file($file) {
  if($file) {
    file_transfer($file->uri, array('Content-disposition', 'attachment; filename='.$file->filename));
  }
  else {
    return drupal_access_denied();
  }
}

/**
 * Implements hook_node_view().
 */
function pnf_documents_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'document' && $view_mode == 'teaser') {
    // Edit link in documents teaser removed for anonymous users or users not allowed to edit document nodes.
    if (user_is_anonymous() || !node_access('update', $node)) {
      unset($node->content['document_edit']);
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
//function pnf_documents_entity_view_alter(&$build, $type) {
//  if ($type == 'field_collection_item' && $build['#bundle'] == 'field_document_links' && $build['#view_mode'] == 'full') {
//    // In documents teaser, if remote doc flip through link exists, local pdf viewing link is removed.
//    if(isset($build['field_document_flip'])) {
//      unset($build['local_flipthrough']);
//    }
//  }
//}
