<?php
/**
 * @file
 * Code for the Documents feature.
 */

include_once 'pnf_documents.features.inc';

/**
 * Implements hook_form_alter().
 */
function pnf_documents_form_alter(&$form, &$form_state, $form_id) {
  // If "Documents" exposed filter, we must remove 'Communiqué de presse' and 'Dossier de presse' options.
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-documents-page-documents') {
    $options = $form['field_document_category_tid']['#options'];
    foreach ($options  as $key => $option) {
      $haystack = array('Communiqué de presse','Dossier de presse');
      if (in_array($option, $haystack)) {
        unset($options[$key]);
      }
    }
    $form['field_document_category_tid']['#options'] = $options;
  }

  // Il "Espace Presse" exposed filter, we must keep only 'All', 'Communiqué de presse' and 'Dossier de presse' options.
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-documents-page-press') {
    $options = $form['field_document_category_tid']['#options'];
    $press_options = array_slice($options,0,1,TRUE);
    foreach ($options  as $key => $option) {
      $haystack = array('Communiqué de presse','Dossier de presse');
      if (in_array($option, $haystack)) {
        $press_options[$key] = $option;
      }
    }
    $form['field_document_category_tid']['#options'] = $press_options;
  }
}

/**
 * Implementation of hook_menu()
 */
function pnf_documents_menu() {
  $items['download/%file'] = array(
    'page callback' => 'pnf_download_file',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Page callback for forcing a file to download
 */
function pnf_download_file($file) {
  if($file) {
    file_transfer($file->uri, array('Content-disposition', 'attachment; filename='.$file->filename));
  }
  else {
    return drupal_access_denied();
  }
}

/**
 * Implements hook_node_view().
 */
function pnf_documents_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'document' && $view_mode == 'teaser') {
    // Edit link in documents teaser removed for anonymous users or users not allowed to edit document nodes.
    if (user_is_anonymous() || !node_access('update', $node)) {
      unset($node->content['document_edit']);
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
//function pnf_documents_entity_view_alter(&$build, $type) {
//  if ($type == 'field_collection_item' && $build['#bundle'] == 'field_document_links' && $build['#view_mode'] == 'full') {
//    // In documents teaser, if remote doc flip through link exists, local pdf viewing link is removed.
//    if(isset($build['field_document_flip'])) {
//      unset($build['local_flipthrough']);
//    }
//  }
//}
