<?php
/**
 * @file
 * Code for the Multimedia feature.
 */

include_once 'pnf_multimedia.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pnf_multimedia_form_scald_atom_add_form_source_alter(&$form, &$form_state, $form_id) {
  if (arg(2) == 'video') {
    unset($form['source']['#options']['scald_video']);
  }
}

/**
 * Implements hook_form_alter().
 */
function pnf_multimedia_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'scald_atom_add_form_options') {
    drupal_add_js(drupal_get_path('module','pnf_multimedia') . '/js/pnf_multimedia.js');
    $form['atom0']['scald_actions']['#weight'] = 100;
  }

  if ($form['#id'] == 'views-exposed-form-multimedia-page-videos') {
    $options = $form['field_media_category_tid']['#options'];
    $purged_options = pnf_multimedia_purge_category_filter($options, 'video');
    $form['field_media_category_tid']['#options'] = $purged_options;
  }

  if ($form['#id'] == 'views-exposed-form-multimedia-page-photos') {
    $options = $form['field_media_category_tid']['#options'];
    $purged_options = pnf_multimedia_purge_category_filter($options, 'gallery');
    $form['field_media_category_tid']['#options'] = $purged_options;
  }

  if ($form['#id'] == 'views-exposed-form-multimedia-page-sounds') {
    $options = $form['field_media_category_tid']['#options'];
    $purged_options = pnf_multimedia_purge_category_filter($options, 'audio');
    $form['field_media_category_tid']['#options'] = $purged_options;
  }
}

/**
 * Helper functions
 */

function pnf_multimedia_purge_category_filter($options, $atom_type) {
  // Seek all tids linked to atoms of $atom_type type.
  $query = db_select('field_data_field_media_category', 'fmc');
  $query->addField('fmc','field_media_category_tid');
  $query->condition('fmc.bundle', $atom_type);
  $query->distinct();
  $used_tids = $query->execute()->fetchCol();

  // Remove terms not linked to video atoms from $options array.
  foreach ($options as $key=>$value) {
    if (is_integer($key)) {
      if (!in_array($key, $used_tids)) {
        unset($options[$key]);
      }

      // In case of gallery view, we must get rid of 'Cartothèque' term, if any.
      if ($atom_type == 'gallery' && $value == 'Cartothèque') {
        unset($options[$key]);
      }
    }
  }

  return $options;
}

/**
 * Implements hook_menu_link_alter().
 */
/**
 * Implements hook_block_view_MODULE_DELTA_alter().
 */
function pnf_multimedia_block_view_alter(&$data, $block) {
  // For parks determined by $park_codes, the Videos link is removed from menu-multimedia-footer.
  if ($block->bid == 'menu-menu-multimedia-footer') {
    $park_codes = array('fcb');
    if (in_array(variable_get('park_code'), $park_codes)) {
      $mlids = element_children($data['content']);
      foreach ($mlids as $mlid) {
        if ($data['content'][$mlid]['#href'] == 'videos') {
          unset($data['content'][$mlid]);
        }
      }
    }
  }
  if ($block->bid == 'menu-menu-multimedia') {
    $park_codes = array('fcb');
    if (in_array(variable_get('park_code'), $park_codes)) {
      $mlids = element_children($data['content']);
      foreach ($mlids as $mlid) {
        if ($data['content'][$mlid]['#href'] == 'videos' || $data['content'][$mlid]['#href'] == 'sons') {
          unset($data['content'][$mlid]);
        }
      }
    }
  }
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function pnf_multimedia_pathauto_alias_alter(&$alias, array &$context) {
  // If gallery category = cartotheque (uuid = 5ed1938d-1c9d-4dff-b885-ea096e718753),
  // we must alter pathauto.
  if ($context['module'] == 'scald_atom') {
    $media_category = $context['data']['scald_atom']->field_media_category;
    $first_value = array_shift($media_category);
    $category_tid = $first_value[0]['tid'];
    $term_wrapper = entity_metadata_wrapper('taxonomy_term', $category_tid);
    $term_uuid = $term_wrapper->value()->uuid;

    if ($term_uuid == '5ed1938d-1c9d-4dff-b885-ea096e718753') {
      $alias = 'cartotheque' . substr($alias, strpos($alias, '/'));
    }

//    dpm($context);
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function pnf_multimedia_entity_view_alter(&$build, $type) {
//  dpm($build);
//  dpm($type);
}
