<?php
/**
 * @file
 * pnf_multimedia.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function pnf_multimedia_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Agriculture',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0352ec79-7872-44af-a434-b167054a9d50',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Faune',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2625b1e0-1d59-41a9-8806-c655e65678af',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Manifestations',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '42b2d8d4-af31-4884-96f2-2d18f5602525',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Flore',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5a27037f-b83d-4fa4-909e-ad73bd87a95c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Culture',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6910845e-08a9-4b67-b255-dc49577390cc',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Découverte',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '728fb2ce-f0bb-4f63-b47d-b51f3f5083de',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => '￼Paysages et patrimoine',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9d50f873-5ed8-46b7-9cb6-f009102876c6',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Loisirs',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a88d2d2a-99d2-4783-a40b-aac485e483f9',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Education à l\'environnement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'aff27c68-b249-44b5-8132-5b9534700db0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  $terms[] = array(
    'name' => 'Economie',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd3467de7-6b2c-4d99-b6c7-c9c2889858f2',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'media_categories',
  );
  return $terms;
}
