<?php
/**
 * @file
 * Code for the Actualités feature.
 */

include_once 'pnf_news.features.inc';

function pnf_news_init() {
  $node = menu_get_object();
  if (!empty($node) && $node->type == "news") {
    drupal_add_js(drupal_get_path('module','pnf_news') . '/js/pnf_news.js');
  }
}

/**
 * Implements hook_node_view().
 */
function pnf_news_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'news') {
    $news_type_object = taxonomy_term_load($node->field_news_type['und'][0]['tid']);
    // If Dossier, displayed date field is removed.
    if ($news_type_object->uuid == 'ada69fa2-d961-472c-82fa-f044f0a166bb') {
      unset($node->content['field_displayed_pub_date']);
    }
    else {
      if ($view_mode == 'full') {
        $displayed_date = $node->content['field_displayed_pub_date'][0]['#markup'];
        $raw_displayed_date = strip_tags($displayed_date);
        $wrapper_parts = explode($raw_displayed_date,$displayed_date);
        $node->content['field_displayed_pub_date'][0]['#markup'] = $wrapper_parts[0]
          . t('On ')
          . $raw_displayed_date
          . $wrapper_parts[1];

        if (empty($node->content['field_downloadable_docs']['#items'])) {
          unset($node->content['field_downloadable_docs']);
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pnf_news_form_news_node_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('park_code') == 'fcb') {
    // We must hide field_public (not used, but compulsory in FCB site).
    $form['field_public']['#access'] = FALSE;

    // We must remove field_sectors (not used in FCB site and not compulsory).
    unset ($form['field_sectors']);

    // We must remove option "Brèves" for news type in FCB site.
    foreach ($form['field_news_type']['und']['#options'] as $key => $option) {
      if ($option == 'Brèves') {
        unset($form['field_news_type']['und']['#options'][$key]);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function pnf_news_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-news-page-news-news') {
    if (variable_get('park_code') == 'fcb') {
      $form['field_sectors_tid']['#access'] = FALSE;
      $form['#info']['filter-field_sectors_tid']['label'] = FALSE;
      $form['field_public_tid']['#access'] = FALSE;
      $form['#info']['filter-field_public_tid']['label'] = FALSE;
    }
  }
}

/**
 * Implements hook_block_view_alter().
 */
function pnf_news_block_view_alter(&$data, $block) {
  // For parks determined by $park_codes, the "Brèves" link is removed from menu_menu_news.
  if ($block->bid == 'menu-menu-news') {
    $park_codes = array('fcb');
    if (in_array(variable_get('park_code'), $park_codes)) {
      $mlids = element_children($data['content']);
      foreach ($mlids as $mlid) {
        if ($data['content'][$mlid]['#href'] == 'breves') {
          unset($data['content'][$mlid]);
        }
      }
    }
  }
}
